CREATE DATABASE IF NOT EXISTS XHH DEFAULT CHARSET UTF8 COLLATE UTF8_GENERAL_CI ;

USE XHH;

DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER(
U_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '用户编号',
U_NAME VARCHAR(30) NOT NULL UNIQUE COMMENT '登录名',
U_PASSWORD VARCHAR(30) NOT NULL UNIQUE COMMENT '登录密码',
U_REALNAME VARCHAR(20) NOT NULL COMMENT '真实姓名',
U_EMAIL VARCHAR(100) NOT NULL UNIQUE COMMENT '邮箱',
U_PHONE VARCHAR(20) UNIQUE COMMENT '手机号',
U_ADDRESS VARCHAR(100) NOT NULL COMMENT '地址',
U_TYPE TINYINT UNSIGNED NOT NULL COMMENT '用户类型 1:系统用户 0:注册会员用户',
U_STATE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1:可用状态  0:删除状态  2:锁定状态',
PRIMARY KEY(U_ID)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT='用户表';
